title: IT Gurukula
email: itgurukulanp@gmail.com
life_cycle: pre-alpha
description: >- # this means to ignore newlines until "baseurl:"
  Cyber Security Syllabus for Workshop conducted under IT Gurukula
baseurl: "/workshop-template" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image_base_url: /assets/img

google_analytics: # your google analytics id

permalink: /:title

contacts:
  github:
    url: https://github.com/itgurukula/
    label: GitHub
    class: bx bxl-github
  email:
    url: mailto:itgurukulanp@gmail.com
    label: Email
    class: bx bx-mail-send

# Build settings
markdown: kramdown
